### ISSUE TITLE
I installed Port and it even added the Source Control menu but the text there is empty!

### ISSUE THREAD

**Issue by redhighknee** [rfns/port#7]
SessionLanguage en-us

Clicking on any Source Control menu item responds [Port] in Studio Output window.  None have text description in menu item. 

Clicking on Source Control menu location corresponding to unit tests results in 1 failure:

HEALTHSHARE
PRECERT
Cache for Windows (x86-64) 2017.2.2 (Build 865_3_19186U) Tue Aug 27 2019 19:43:13 EDT
2019-10-01 15:52:58
  | 1 | AssertEquals | passed | Can translate Windows to Unix path
  | 2 | AssertEquals | failed | Can translate Unix to Windows path
  | 3 | AssertEquals | passed | Can fix erroneous Windows paths
  | 4 | AssertEquals | passed | Can fix erroneous Unix paths
  | 5 | LogMessage | passed | Duration of execution: .061445 sec.
 
 Any suggestions?

Thank you.

**Comment by rfns** [comment]
Hello @redhighknee 

Can you tell me which default language is your Caché Studio using? Port actually supports two languages: pt-BR and english, if your Studio is not using one of them you'll have the issue with blank menus.

Looks like I need to assume manually that english is the default if there isn't one available.

**Comment by redhighknee** [comment]
Studio is installed with default English.  I did try installing with the session “en-us” setting as described in the documentation.  No difference.

There's no place like 127.0.0.1

On Oct 2, 2019, at 06:28, Rubens F. N. da Silva <notifications@github.com<mailto:notifications@github.com>> wrote:


Hello @redhighknee<https://github.com/redhighknee>

Can you tell me which default language is your Caché Studio using? Port actually supports two languages: pt-BR and english, if your Studio is not using one of them you'll have the issue with blank menus.

Looks like I need to assume manually that english is the default if there isn't one available.

**Comment by redhighknee** [comment]
Looks like the session language is not "en-us" but only "en".

BZHCATSVR>W ##class(%MessageDictionary).GetSessionLanguage()
en


BZHCATSVR>zw ^CacheMsg("Port Menu Labels")
^CacheMsg("Port Menu Labels","en-us",-5010)="Import (forced)"
^CacheMsg("Port Menu Labels","en-us",-5009)="Export (forced)"
^CacheMsg("Port Menu Labels","en-us",-5008)="Import"
^CacheMsg("Port Menu Labels","en-us",-5007)="Run tests"
^CacheMsg("Port Menu Labels","en-us",-5006)="Scan and fix"
^CacheMsg("Port Menu Labels","en-us",-5005)="Remove routines"
^CacheMsg("Port Menu Labels","en-us",-5004)="Remove files"
^CacheMsg("Port Menu Labels","en-us",-5003)="Remove classes"
^CacheMsg("Port Menu Labels","en-us",-5002)="Export tests"
^CacheMsg("Port Menu Labels","en-us",-5001)="Export to XML"
^CacheMsg("Port Menu Labels","en-us",-5000)="Export"
^CacheMsg("Port Menu Labels","pt-br",-5010)="Importar (forÃ§ado)"
^CacheMsg("Port Menu Labels","pt-br",-5009)="Exportar (forÃ§ado)"
^CacheMsg("Port Menu Labels","pt-br",-5008)="Importar"
^CacheMsg("Port Menu Labels","pt-br",-5007)="Executar testes"
^CacheMsg("Port Menu Labels","pt-br",-5006)="Verificar e corrigir"
^CacheMsg("Port Menu Labels","pt-br",-5005)="Remover rotinas"
^CacheMsg("Port Menu Labels","pt-br",-5004)="Remover arquivos"
^CacheMsg("Port Menu Labels","pt-br",-5003)="Remover classes"
^CacheMsg("Port Menu Labels","pt-br",-5002)="Exportar testes"
^CacheMsg("Port Menu Labels","pt-br",-5001)="Exportar para XML"
^CacheMsg("Port Menu Labels","pt-br",-5000)="Exportar"

BZHCATSVR>zw ^CacheMsgNames("Port Menu Labels")
^CacheMsgNames("Port Menu Labels",-5010)="MLForceImport"
^CacheMsgNames("Port Menu Labels",-5009)="MLForceExport"
^CacheMsgNames("Port Menu Labels",-5008)="MLImport"
^CacheMsgNames("Port Menu Labels",-5007)="MLRunTests"
^CacheMsgNames("Port Menu Labels",-5006)="MLScanAndFix"
^CacheMsgNames("Port Menu Labels",-5005)="MLRemoveRoutines"
^CacheMsgNames("Port Menu Labels",-5004)="MLRemoveFiles"
^CacheMsgNames("Port Menu Labels",-5003)="MLRemoveClasses"
^CacheMsgNames("Port Menu Labels",-5002)="MLExportTests"
^CacheMsgNames("Port Menu Labels",-5001)="MLExportToXML"
^CacheMsgNames("Port Menu Labels",-5000)="MLExport"

BZHCATSVR>d ##class(Port.Installer).CreateMessageDictionary

D ##CLASS(Port.Installer).CreateMessageDictionary()  No difference after Studio restart:
[cid:75e3fb5f-8e9c-4954-bb5c-ff02edc00d40]


I changed the Port.Installer XData LocaleEN to Language="en"
XData LocaleEN [ XMLNamespace = "https://github.com/rfns/port" ]
{
<?xml version="1.0" encoding="UTF-8"?>
<MsgFile Language="en">

and then ran the installer again with force=1.

s rslt= ##class(Port.Installer).Install(1.)

Installing Port ... please wait a moment.
> Creating Message Dictionary ...
> Creating global mappings ...
> Global is already mapped. Skipping ...
> Setting up workspace structure ...
> Setting up test files directory ...
> Defining default test class prefix ..
> Configuring to run tests automatically ...
> Configuring to export the project to XML automatically ...
> Configuring log verbosity level to recommended level ...
> Registering source control log cleaner task for BZHCATSVR ...
> Installing %SourceControl hooks and activating it ...

ALL DONE.
NOTE: You must restart Studio in order to make the source control hooks work as expected.

and it appears to be working now:
[cid:02d35f7c-0da4-4619-973f-660e55527627]

I was successful with my first project export.

Thank you,

Red
________________________________

**Comment by rfns** [comment]
@redhighknee fantastic!

Either way, I'll be closing this issue and adding "en" as well to prevent this from happening again.

Thank you for the report.
